global:
  scrape_interval: 15s  # How often to scrape targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']

  - job_name: 'app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app-container:8080']
