- hosts: all
  become: true
  tasks:
    - name: Pull latest Docker image
      shell: "docker pull localhost:5000/my_app:{{ artifact_version }}"

    - name: Run application container
      shell: >
        docker run -d --name app-container -p 8080:8080
        localhost:5000/my_app:{{ artifact_version }}
